-- MySQL Script generated by MySQL Workbench
-- Mon Nov 21 14:17:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wildify_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wildify_db` ;

-- -----------------------------------------------------
-- Schema wildify_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wildify_db` DEFAULT CHARACTER SET utf8 ;
USE `wildify_db` ;

-- -----------------------------------------------------
-- Table `wildify_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wildify_db`.`user` ;

CREATE TABLE IF NOT EXISTS `wildify_db`.`user` (
  `ID_user` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `username` VARCHAR(255) NOT NULL,
  `birthday` VARCHAR(10) NULL,
  `country` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'user',
  PRIMARY KEY (`ID_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wildify_db`.`album` ;

CREATE TABLE IF NOT EXISTS `wildify_db`.`album` (
  `ID_album` INT NOT NULL AUTO_INCREMENT,
  `user_ID_user` INT NULL,
  `albumName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_album`),
  INDEX `fk_album_user1_idx` (`user_ID_user` ASC) VISIBLE,
  CONSTRAINT `fk_album_user1`
    FOREIGN KEY (`user_ID_user`)
    REFERENCES `wildify_db`.`user` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wildify_db`.`playlist` ;

CREATE TABLE IF NOT EXISTS `wildify_db`.`playlist` (
  `ID_playlist` INT NOT NULL AUTO_INCREMENT,
  `user_ID_user` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `creationDate` DATETIME NULL,
  PRIMARY KEY (`ID_playlist`, `user_ID_user`),
  INDEX `fk_playlist_user1_idx` (`user_ID_user` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_user1`
    FOREIGN KEY (`user_ID_user`)
    REFERENCES `wildify_db`.`user` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wildify_db`.`genre` ;

CREATE TABLE IF NOT EXISTS `wildify_db`.`genre` (
  `ID_genre` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`songs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wildify_db`.`songs` ;

CREATE TABLE IF NOT EXISTS `wildify_db`.`songs` (
  `ID_song` INT NOT NULL AUTO_INCREMENT,
  `genre_ID_genre` INT NOT NULL,
  `user_ID_user` INT NULL,
  `title` VARCHAR(255) NOT NULL,
  `artist` VARCHAR(255) NOT NULL,
  `image_url` TEXT NULL,
  `song_url` TEXT NOT NULL,
  PRIMARY KEY (`ID_song`, `genre_ID_genre`),
  INDEX `fk_songs_genre1_idx` (`genre_ID_genre` ASC) VISIBLE,
  INDEX `fk_songs_user1_idx` (`user_ID_user` ASC) VISIBLE,
  CONSTRAINT `fk_songs_genre1`
    FOREIGN KEY (`genre_ID_genre`)
    REFERENCES `wildify_db`.`genre` (`ID_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_user1`
    FOREIGN KEY (`user_ID_user`)
    REFERENCES `wildify_db`.`user` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`playlist_songs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wildify_db`.`playlist_songs` ;

CREATE TABLE IF NOT EXISTS `wildify_db`.`playlist_songs` (
  `playlist_ID_playlist` INT NOT NULL,
  `songs_ID_song` INT NOT NULL,
  INDEX `fk_playlist_song_songs1_idx` (`songs_ID_song` ASC) VISIBLE,
  PRIMARY KEY (`playlist_ID_playlist`, `songs_ID_song`),
  CONSTRAINT `fk_playlist_song_playlist1`
    FOREIGN KEY (`playlist_ID_playlist`)
    REFERENCES `wildify_db`.`playlist` (`ID_playlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_song_songs1`
    FOREIGN KEY (`songs_ID_song`)
    REFERENCES `wildify_db`.`songs` (`ID_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`album_songs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wildify_db`.`album_songs` ;

CREATE TABLE IF NOT EXISTS `wildify_db`.`album_songs` (
  `album_ID_album` INT NOT NULL,
  `songs_ID_song` INT NOT NULL,
  INDEX `fk_album_songs_songs1_idx` (`songs_ID_song` ASC) VISIBLE,
  PRIMARY KEY (`album_ID_album`, `songs_ID_song`),
  CONSTRAINT `fk_album_songs_album1`
    FOREIGN KEY (`album_ID_album`)
    REFERENCES `wildify_db`.`album` (`ID_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_songs_songs1`
    FOREIGN KEY (`songs_ID_song`)
    REFERENCES `wildify_db`.`songs` (`ID_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wildify_db`.`like` ;

CREATE TABLE IF NOT EXISTS `wildify_db`.`like` (
  `ID_like` INT NOT NULL AUTO_INCREMENT,
  `user_ID_user` INT NOT NULL,
  `songs_ID_song` INT NOT NULL,
  PRIMARY KEY (`ID_like`, `user_ID_user`, `songs_ID_song`),
  INDEX `fk_like_songs1_idx` (`songs_ID_song` ASC) VISIBLE,
  INDEX `fk_like_user1_idx` (`user_ID_user` ASC) VISIBLE,
  CONSTRAINT `fk_like_songs1`
    FOREIGN KEY (`songs_ID_song`)
    REFERENCES `wildify_db`.`songs` (`ID_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`user_ID_user`)
    REFERENCES `wildify_db`.`user` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
