-- Active: 1665738240583@@mysql@null@checkpoint1
-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 14:58:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wildify_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wildify_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wildify_db` DEFAULT CHARACTER SET utf8 ;
USE `wildify_db` ;

-- -----------------------------------------------------
-- Table `wildify_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildify_db`.`user` (
  `ID_user` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(150) NOT NULL,
  `lastname` VARCHAR(150) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `dob` DATE NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'user',
  PRIMARY KEY (`ID_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildify_db`.`genre` (
  `ID_genre` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildify_db`.`songs` (
  `ID_song` INT NOT NULL AUTO_INCREMENT,
  `user_ID_user` INT NOT NULL,
  `genre_ID_genre` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `like` TINYINT NULL,
  `image_url` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_song`, `user_ID_user`, `genre_ID_genre`),
  INDEX `fk_songs_user_idx` (`user_ID_user` ASC) VISIBLE,
  INDEX `fk_songs_genre1_idx` (`genre_ID_genre` ASC) VISIBLE,
  CONSTRAINT `fk_songs_user`
    FOREIGN KEY (`user_ID_user`)
    REFERENCES `wildify_db`.`user` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_genre1`
    FOREIGN KEY (`genre_ID_genre`)
    REFERENCES `wildify_db`.`genre` (`ID_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildify_db`.`album` (
  `ID_album` INT NOT NULL AUTO_INCREMENT,
  `songs_ID_song` INT NOT NULL,
  `user_ID_user` INT NOT NULL,
  `albumName` VARCHAR(255) NOT NULL,
  `releaseDate` DATE NULL,
  PRIMARY KEY (`ID_album`, `songs_ID_song`, `user_ID_user`),
  INDEX `fk_album_songs1_idx` (`songs_ID_song` ASC) VISIBLE,
  INDEX `fk_album_user1_idx` (`user_ID_user` ASC) VISIBLE,
  CONSTRAINT `fk_album_songs1`
    FOREIGN KEY (`songs_ID_song`)
    REFERENCES `wildify_db`.`songs` (`ID_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_user1`
    FOREIGN KEY (`user_ID_user`)
    REFERENCES `wildify_db`.`user` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildify_db`.`playlist` (
  `ID_playlist` INT NOT NULL AUTO_INCREMENT,
  `user_ID_user` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `creationDate` DATE NULL,
  PRIMARY KEY (`ID_playlist`, `user_ID_user`),
  INDEX `fk_playlist_user1_idx` (`user_ID_user` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_user1`
    FOREIGN KEY (`user_ID_user`)
    REFERENCES `wildify_db`.`user` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildify_db`.`playlist_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildify_db`.`playlist_song` (
  `playlist_ID_playlist` INT NOT NULL,
  `songs_ID_song` INT NOT NULL,
  PRIMARY KEY (`playlist_ID_playlist`, `songs_ID_song`),
  INDEX `fk_playlist_song_songs1_idx` (`songs_ID_song` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_song_playlist1`
    FOREIGN KEY (`playlist_ID_playlist`)
    REFERENCES `wildify_db`.`playlist` (`ID_playlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_song_songs1`
    FOREIGN KEY (`songs_ID_song`)
    REFERENCES `wildify_db`.`songs` (`ID_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;